//1
let a 
a = 10
alert(a)
a = 20
alert(a)

//2
let iphon = 2007
alert(iphon)

//3
const name='Брендан Эйх'

//4
let first = 10
let second = 2
alert(first + second)
alert(first - second)
alert(first * second)
alert(first / second)

//5
let result = 2**5
alert (result)

//6
a = 9
let b = 2
let c = a % b
alert(c)

//7
let num = 1
num += 5
num -= 3
num *=7
num /=3
num++
num--
alert(num)

//8
let age = Number(prompt('Сколько вам лет?'))
alert(age)

//9
let user = {
    name: 'mark',
    age: 17,
    isAdmin: false
}

//10
let person = Number(prompt('Какое ваше имя?'))
alert('Привет ' + person + '!')